import type { Column } from "~/models/column";

export const encounterColumns: Column[] = [
  {
    key: "count",
    label: "Number",
    sortable: true,
  },
  {
    key: "name",
    label: "Name",
    sortable: true,
    type: "string",
  },
  {
    key: "challenge_type",
    label: "Type",
  },
  {
    key: "action",
    label: "Action",
  },
];

export const columns: Column[] = [
  {
    key: "name",
    label: "Name",
    width: "250px",
    sortable: true,
    filterable: true,
    type: "string",
  },
  {
    key: "level",
    label: "Level",
    width: "50px",
    sortable: true,
    filterable: true,
    matchMode: "gte",
    type: "number",
    minValue: -1,
    maxValue: 25,
  },
  {
    key: "creature_family",
    markdownField: "creature_family_markdown",
    label: "Family",
    width: "250px",
    sortable: true,
    filterable: true,
    type: "dropdown",
    select: "multiple",
    matchMode: "in",
    getUniqueValues: true,
  },
  {
    key: "trait_raw",
    markdownField: "trait_markdown",
    label: "Traits",
    width: "250px",
    sortable: true,
    filterable: true,
    type: "dropdown",
    select: "multiple",
    containsMultipleValues: true,
    matchMode: "in",
    getUniqueValues: true,
  },
  {
    key: "alignment",
    label: "Alignment",
    width: "50px",
    filterable: true,
    type: "dropdown",
    select: "multiple",
    matchMode: "in",
    selectionOptions: [
      { label: "Any", value: "Any" },
      { label: "Lawful Good", value: "LG" },
      { label: "Lawful Neutral", value: "LN" },
      { label: "Lawful Evil", value: "LE" },
      { label: "Neutral Good", value: "NG" },
      { label: "True Neutral", value: "TN" },
      { label: "Neutral Evil", value: "NE" },
      { label: "Chaotic Good", value: "CG" },
      { label: "Chaotic Neutral", value: "CE" },
      { label: "Chaotic Evil", value: "CE" },
      { label: "No Alignment", value: "No Alignment" },
    ],
  },
  {
    key: "action",
    width: "5%",
    label: "Action",
    filterable: false,
  },
];
