import type { Filter } from "~/models/filter";

export const filterConfig: Filter[] = [
  {
    key: "name",
    label: "Name",
    matchMode: "contains",
    type: "string",
  },
  {
    key: "level_min",
    label: "Min Level",
    matchMode: "gte",
    type: "number",
    minValue: -1,
    maxValue: 25,
  },
  {
    key: "level_max",
    label: "Max Level",
    matchMode: "lte",
    type: "number",
    minValue: -1,
    maxValue: 25,
  },
  {
    key: "size",
    label: "Size",
    type: "dropdown",
    select: "multiple",
    matchMode: "in",
    containsMultipleValues: true,
    selectionOptions: [
      { label: "Tiny", value: "Tiny" },
      { label: "Small", value: "Small" },
      { label: "Medium", value: "Medium" },
      { label: "Large", value: "Large" },
      { label: "Huge", value: "Huge" },
      { label: "Gargantuan ", value: "Gargantuan" },
    ],
  },
  {
    key: "creature_family",
    label: "Family",
    type: "dropdown",
    select: "multiple",
    matchMode: "in",
    getUniqueValues: true,
  },
  {
    key: "trait_raw",
    label: "Traits",
    type: "dropdown",
    select: "multiple",
    containsMultipleValues: true,
    matchMode: "in",
    getUniqueValues: true,
  },
  {
    key: "alignment",
    label: "Alignment",
    type: "dropdown",
    select: "multiple",
    matchMode: "in",
    selectionOptions: [
      { label: "Any", value: "Any" },
      { label: "Lawful Good", value: "LG" },
      { label: "Lawful Neutral", value: "LN" },
      { label: "Lawful Evil", value: "LE" },
      { label: "Neutral Good", value: "NG" },
      { label: "True Neutral", value: "TN" },
      { label: "Neutral Evil", value: "NE" },
      { label: "Chaotic Good", value: "CG" },
      { label: "Chaotic Neutral", value: "CE" },
      { label: "Chaotic Evil", value: "CE" },
      { label: "No Alignment", value: "No Alignment" },
    ],
  },
  {
    key: "npc",
    label: "Type",
    type: "dropdown",
    select: "single",
    matchMode: "contains",
    selectionOptions: [
      { label: "Creature", value: false },
      { label: "NPC", value: "true" },
    ],
  },
];
